### ISSUE TITLE
Does not work in blade files

### ISSUE THREAD

**Issue by georgeboot** [inxilpro/IntellijAlpine#1]
This plugin does not work in `*.blade.php` files. How hard would it be to enable it to also work in those templates files?

**Comment by inxilpro** [comment]
Hm. It works fine in Blade files for me… What version of PhpStorm are you using?

**Comment by georgeboot** [comment]
I'm using 2020.2 on MacOS.

I'll have to rephrase: the autocomplete somewhat works, but it's marking all of my alpine tags as not allowed:
<img width="714" alt="Schermafbeelding 2020-11-02 om 15 31 08" src="https://user-images.githubusercontent.com/884482/97879665-8b68eb00-1d20-11eb-8608-1bf0c34f5d2c.png">

`x-data` also always errors:
<img width="397" alt="Schermafbeelding 2020-11-02 om 15 32 35" src="https://user-images.githubusercontent.com/884482/97879798-ad626d80-1d20-11eb-9737-155469dbd2e7.png">

**Comment by inxilpro** [comment]
Oh, those are Livewire attributes, not Alpine.js. I'm pretty sure that https://laravel-idea.com/ offers Livewire attribute support.
