### ISSUE TITLE
"Thin arrow used" error occurs in the blade file.

### ISSUE THREAD

**Issue by mertasan** [inxilpro/IntellijAlpine#10]
```blade
<input x-ref="{{ $field->key }}" {{ $field->wire }}="{{ $field->key }}" name="{{ $field->key }}" type="hidden"
autocomplete="{{ $field->autocomplete }}" class="nosy" />
```

![thin_arrow_used](https://user-images.githubusercontent.com/13007665/103448559-3dcf1700-4cac-11eb-85c0-b73cfffe8eec.gif)

Details about the problem are on the url.

https://youtrack.jetbrains.com/issue/WI-57838

**Comment by lh-s-net** [comment]
Is an update planned?

**Comment by inxilpro** [comment]
It appears that the Alpine language injection (telling the IDE that what's inside an `x-` directive is JS) is overriding the Laravel language injection (telling the IDE that what's inside `{{` is PHP. I'll have to dig around to see if there's a way to change that priority…

**Comment by mertasan** [comment]
@inxilpro I uninstalled the plugin a few months ago because of this issue. I would like to use it again if the bug is fixed. 👍

**Comment by inxilpro** [comment]
I think 0.4.0 will resolve this. I'm still testing it a bit, but should be able to release it in a day or two.

**Comment by inxilpro** [comment]
I can confirm that this will work in 0.4.0:

![image](https://user-images.githubusercontent.com/21592/121930306-3c505300-cd10-11eb-8353-8852f87cad6e.png)

**Comment by mertasan** [comment]
thank you! @inxilpro
