### ISSUE TITLE
Auto-complete alpine directives for example x-show.transition, x-on:keydown.escape etc..

### ISSUE THREAD

**Issue by EOM** [inxilpro/IntellijAlpine#14]
Hi is good
Auto-complete alpine directives for example
x-show.**transition**
x-show.**transition.scale.75**
x-on:click.**away**
x-on:keydown.**escape**
x-on:directives.**xxxxx.xxx**
etc..

Add feature is cool ;)
Saludos de Argentina

**Comment by inxilpro** [comment]
This is coming in 0.4.0:

![intellij-alpine-beta](https://user-images.githubusercontent.com/21592/121930186-16c34980-cd10-11eb-983c-ce761a5a2bf2.gif)
