### ISSUE TITLE
php echo in javascript triggers error

### ISSUE THREAD

**Issue by tschallacka** [inxilpro/IntellijAlpine#17]
Echoing data from php within the javascript marked x- attributes gives an error.

```
   x-data="some_method(<?= $alpine_options ?>)"
```

![image](https://user-images.githubusercontent.com/8638425/119989494-870b6480-bfc7-11eb-8bad-ebe159ffc0c8.png)

**Comment by inxilpro** [comment]
This should be fixed in the upcoming 0.4.0:

![image](https://user-images.githubusercontent.com/21592/121930163-0ca14b00-cd10-11eb-82ee-c5e6e39ba6a9.png)
