### ISSUE TITLE
x-on and x-bind are Unbound XML namespace prefixes

### ISSUE THREAD

**Issue by tschallacka** [inxilpro/IntellijAlpine#18]
x-on and x-bind are thrown up as error 'Unbound XML namespace prefix'

![image](https://user-images.githubusercontent.com/8638425/119990187-5546cd80-bfc8-11eb-898c-5e30f7051469.png)

I resolved it for now by adjusting the inspection settings to only fix, don't highlight, but that's just a short term solution

![image](https://user-images.githubusercontent.com/8638425/119990424-9808a580-bfc8-11eb-84f6-fb8cbf2a43bb.png)

**Comment by inxilpro** [comment]
This should be resolved in the latest version.
