### ISSUE TITLE
Please, support Alpine plugins (`x-intersect`, `$persist` for now)

### ISSUE THREAD

**Issue by dmitry-ivanov** [inxilpro/IntellijAlpine#23]
Hi,

Thank you for your work and the great plugin you've created and continue to maintain! 🙏

Alpine 3 has a plugins system, and there are a couple of plugins officially released:
https://alpinejs.dev/plugins/intersect
https://alpinejs.dev/plugins/persist

It would be awesome to have them supported by your plugin too.

Thank you,
Have a great day and keep doing a great job! 👍

**Comment by inxilpro** [comment]
Thanks for the suggestion! `$persist()` (and `$queryString()`) were actually already partially supported, but they didn't work inside of `x-data`. The next plugin release should fix that and add `x-intersect` to the autocomplete definition.

**Comment by dmitry-ivanov** [comment]
@inxilpro Thanks for releasing the `0.4.1`! 👍

Just wanted to let you know that `x-intersect` is autocompleted now, but there's a warning _(other directives work fine, see `x-init` on the image, for example)_:

![x-intersect](https://user-images.githubusercontent.com/1286821/127212217-d1a3ac5c-b644-4dfd-ad19-96e24ee6b929.png)

I'm not sure, but maybe it's related to the plugin itself?

Thank you!
