### ISSUE TITLE
Some keyboard keys not working when cursor is placed next to the quotations

### ISSUE THREAD

**Issue by sadrahkm** [inxilpro/IntellijAlpine#24]
I'm using Phptorm 2019.3 and Windows 10. 
When my cursor is placed next to the quotations, I can't press some keyboard keys like Enter or open parenthesis.
![image](https://user-images.githubusercontent.com/17474500/127736579-38cc328b-1fac-4b0c-9fbf-887baac918e4.png)
As shown in above picture, you can't press enter right there and it doesn't allow you to use some specific keywords.
Also I can't use open parenthesis in alpine directives.
Please reproduce it and tell me if it's my IDE's issue

**Comment by inxilpro** [comment]
Yeah, this is a known issue. I don't have a perfect solution for it, but I have an idea that I'll try to include in the next release.
