### ISSUE TITLE
in PHPStorm 2021.1.4 plugin just throwing an exception/error when it tries to search for relation to input "x-..."

### ISSUE THREAD

**Issue by patarok** [inxilpro/IntellijAlpine#25]
I just tried to put the plugin to good use, but when i type in f.i. just an 'x' and a '-' like : 'x-' in some tag, phpstorm says your plugin threw an error.
have a look at:
https://pastebin.com/5uDUEKTE

**Comment by patarok** [comment]
FYI: that has gone away after the first 3-4 times i tried to type:
 x-
 but i guess the fact that this happens at all... may point out, there is something that needs a fix? Or is it just my machine?

**Comment by inxilpro** [comment]
Hm. Looks like maybe this is an interaction between the Angular 2 plugin and the Alpine plugin. I'll see what I can figure out. But you said it's stopped happening for you?
