### ISSUE TITLE
x-id is not recognized

### ISSUE THREAD

**Issue by slaFFik** [inxilpro/IntellijAlpine#29]
`x-on` is recognized by the plugin while `x-id` is not.

![image](https://user-images.githubusercontent.com/282234/172027340-dccd4cd7-cd2d-419e-8083-4cb62d0f2842.png)

Using Alpine.js v3.10.2.
Plugin version: v0.4.2

**Comment by inxilpro** [comment]
Should be fixed in 0.5.0 (which will be out soon)!
