### ISSUE TITLE
Attribute Highlighting

### ISSUE THREAD

**Issue by leecolarelli** [inxilpro/IntellijAlpine#3]
Firstly thanks for the great plugin! Just what i was looking for.

Is it in the plans to stop PHPStorm highlighting x- syntax? Currently it shows `Attribute x-data is not allowed here` in blade files, and strangely also says `Rename attribute to x-data` which does not do anything. 

A small issue I know :)

Thanks again.

**Comment by inxilpro** [comment]
Hm. I don't have this issue at all…

<img width="612" alt="image" src="https://user-images.githubusercontent.com/21592/100239911-f82a6c00-2eff-11eb-8252-c3fdabce1850.png">

<img width="323" alt="image" src="https://user-images.githubusercontent.com/21592/100239880-ed6fd700-2eff-11eb-804b-9fd2ecc003db.png">
