### ISSUE TITLE
Support for html attributes on Rails helpers

### ISSUE THREAD

**Issue by DanielJackson-Oslo** [inxilpro/IntellijAlpine#33]
Thanks for taking the time to write this plugin! 

For my use case, I would love to see support for Alpine in Rails helpers, like this: 

```erb

<%= form_with @model, html: { "x-data": "Alpine comes here"  } %>

```

I know you haven't had the motivation to maintain this for the last few years (and have no obligation to do so, either!) so even though I don't know Kotlin I would love to help you out and try to write, or help write, the code to make this possible.

From what I can tell from reviewing the code base, it currently relies on standard IntelliJ modules to parse HTML, right? So the first question would be if there's a standard IntelliJ way to parse html attributes in Rails helpers, or if I have to write a regex or something to parse them? Does anyone know?

**Comment by inxilpro** [comment]
Hm. I know nothing about Rails or how IntelliJ handles Ruby. I would assume there's some language injection component, so I'd look into figuring out how to tell the IDE where to inject JS into that snippet. That's really all the plugin does right now (it's just telling the IDE that everything inside the `x-data` attribute is JS and providing a little context).
