### ISSUE TITLE
Version 0.5.0 is marked as incompatible with PhpStorm 2023.2

### ISSUE THREAD

**Issue by ThomasEnssner** [inxilpro/IntellijAlpine#41]
When using PhpStorm 2023.2 the plugin drops back to v0.4.2 because of of the build number of the IDE:

> Plugin 'Alpine.js Support' (version '0.5.0') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is PS-232.8660.205

**Comment by inxilpro** [comment]
I just submitted version `0.6.0` to Jetbrains. It should be available shortly (there's a review process, so it might not be until tomorrow or the day after).

Cheers!
