### ISSUE TITLE
Plugin not activating

### ISSUE THREAD

**Issue by rickythefox** [inxilpro/IntellijAlpine#47]
![image](https://github.com/inxilpro/IntellijAlpine/assets/1675955/5e93461b-1980-4b71-9300-34401dddb80f)

Do I need to do anything to get WebStorm to recognize the Alpine directives in a .html-file?

**Comment by reatlat** [comment]
Same issue on one machine, but works well on another, machines have same version of plugin and WebStorm, settings are synced

**Comment by reatlat** [comment]
@rickythefox I just fixed on my instance, I did uninstall WebStorm and cleaned [configs folders](https://www.jetbrains.com/help/webstorm/configuring-project-and-ide-settings.html#b9ab3505) 
after install WebStorm and importing settings and install plugins, Alpine support back to my WebStorm :)
