### ISSUE TITLE
Formatting for @event vs x-on:event for custom events

### ISSUE THREAD

**Issue by praetoros** [inxilpro/IntellijAlpine#49]
![image](https://github.com/inxilpro/IntellijAlpine/assets/84818257/b0131eb7-6965-4119-b53a-74b574c2fc68)

As far as I can tell, both of these should be valid, but I am getting an error "Namespace '@htmx' is not bound" with the top line, I assume due to the `:`.

`@htmx:confirm=""`
`x-on:htmx:confirm=""`

**Comment by inxilpro** [comment]
Hm, yeah. I'm not really sure about how this would be impacted by HTMX. Honestly, that's probably outside of the scope of this plugin. Technically `@htmx:confirm` is not valid XML, but it works just fine. I'd be happy to look at a PR, but I'm not sure that this plugin will ever work great with HTMX…
