### ISSUE TITLE
Nested x-data prompts errors in PyCharm

### ISSUE THREAD

**Issue by GeorgeFlorian** [inxilpro/IntellijAlpine#50]
Hello.
I am using AlpineJS Support 0.6.0 and I get an error in PyCharm 2023.1.1 when using nested `x-data`
![image](https://github.com/inxilpro/IntellijAlpine/assets/39895513/4d40cdc3-080d-4f5b-a1c0-4d9b88631f27)

As you can see from the above image, the second `errorMsg` is grayed out.
The error reads: `Unresolved variable or type errorMsg`
The code works. Here is the pen: https://codepen.io/bleah1/pen/zYeveMx

I also get `Attribute @click is not allowed here` for both `@click="show = !show"` on the SVGs.

**Comment by inxilpro** [comment]
This should be resolved in the upcoming release!
