### ISSUE TITLE
Update supported versions for ide, Alpine.js plugin v6.0 can not be used in PhpStorm 2023.3.*

### ISSUE THREAD

**Issue by Oleksandr-Moik** [inxilpro/IntellijAlpine#53]
Update the Compatibility Range for the latest plugin version.

![image](https://github.com/inxilpro/IntellijAlpine/assets/50796878/e26dcda4-5b24-4a67-a3f2-c421d4d942ee)

I use PhpStorm 2023.3 but installed plugin version is 0.4.2.
 
![image](https://github.com/inxilpro/IntellijAlpine/assets/50796878/3e9040ff-449a-47e8-bf46-9d3b8611ebf6)

 
And if I try to install the plugin from the disk, an error occurs

![image](https://github.com/inxilpro/IntellijAlpine/assets/50796878/690df426-004c-458b-9f43-ed1a7c8fdea5)

**Comment by inxilpro** [comment]
This should be resolved in `v0.6.2`!
