### ISSUE TITLE
Does this work with Twig files?

### ISSUE THREAD

**Issue by anugupta** [inxilpro/IntellijAlpine#6]
It doesn't seem to. 

As an example:
```
    <div class="relative flex items-center "
         x-data="youtube()"
         x-init="init('{{ youtube_id }}',
				{
					autoplay: true,
					remember: false,
					aspect_ratio: {{ aspect_ratio }}
				})"
```

 `attribute x-data is not allowed here`
`attribute x-init is not allowed here`

Plugin version 0.0.6 installed.

**Comment by inxilpro** [comment]
Hm. I don't use Twig so I don't really know. Feel free to submit a PR!

**Comment by JUVOJustin** [comment]
Old thread, but i am noticing the same thing. No experience with plugins to open a PR
