### ISSUE TITLE
Syntax colorimetry problem

### ISSUE THREAD

**Issue by acurria** [inxilpro/IntellijAlpine#60]
Hello, 

I've downloaded the latest version of the PhPStorm plugin (0.6.3).
The plugin recognizes Alpine.js directives, but when I make changes to my code, an error systematically appears that distorts/blocks the syntax colorimetry of the code.

![Capture d’écran 2024-01-10 à 14 50 32](https://github.com/inxilpro/IntellijAlpine/assets/69369908/28bbbb2c-e974-441f-a77a-df9b2e5da03a)

My PHPStorm version : 
<img width="422" alt="Capture d’écran 2024-01-10 à 14 52 56" src="https://github.com/inxilpro/IntellijAlpine/assets/69369908/709fb735-4569-4e91-b6fb-14c4ee1c9704">

**Comment by joffreypersia** [comment]
Same here, it is caused by the plugin on complex blade files.  I have to work on an other IDE during the fix time of the dev (if it gets fix)

**Comment by inxilpro** [comment]
I just submitted `v0.6.4` for review, which should address some performance issues. Please let me know if the issue persists after updating!

**Comment by joffreypersia** [comment]
@inxilpro Hi, I still have a lot of bugs.

**Comment by inxilpro** [comment]
@joffreypersia can you post a gist of a blade file that triggers errors?

**Comment by inxilpro** [comment]
Oh, I just saw that you opened a new ticket. Perfect, thanks!
