### ISSUE TITLE
AlpineJS makes PHPStorm crash on complex files

### ISSUE THREAD

**Issue by joffreypersia** [inxilpro/IntellijAlpine#61]
Hi, 

Thank you for this great piece of software, but the problem seems to be linked to the AlpineJS plugin. 

I initially wrote a ticket to PHPStorm, but without ALpineJS, the IDE doesn't crash. 

https://youtrack.jetbrains.com/issue/WEB-64951

Can you take a look? 
On complex code, AlpineJS makes the IDE crash. 

Thank you

**Comment by inxilpro** [comment]
I just submitted `v0.6.4` for review, which should address some performance issues. Please let me know if the issue persists after updating!
