### ISSUE TITLE
Enabling?

### ISSUE THREAD

**Issue by cboden** [inxilpro/IntellijAlpine#8]
Is there anything I need to do to get the plugin working? I installed it through the market place, restarted my IDE, and confirmed the plugin was enabled. In `.html` files I get errors shown in this screenshot:

<img width="754" alt="Screen Shot 2020-12-22 at 4 17 40 PM" src="https://user-images.githubusercontent.com/617694/102934042-6582db80-4471-11eb-846a-42fed90b9475.png">

**Comment by heidilux** [comment]
What I ended up doing was adding all the Alpine directives to Preferences > Editor > Inspections > HTML > Unknown HTML tag attribute. Saw this workaround on SO somewhere.

**Comment by inxilpro** [comment]
Give [the latest release](https://github.com/inxilpro/IntellijAlpine/releases/tag/v0.3.0) a shot!
